// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/offline_sync_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9107254583230726546),
    name: 'OfflineSyncRecord',
    lastPropertyId: const obx_int.IdUid(9, 8922167803272805751),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1345220678252556207),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3289595506263569904),
        name: 'cacheKey',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 3770003775933858745),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5755707226838329373),
        name: 'modelType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3551551265418361290),
        name: 'recordUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7538036441123904072),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6499086407427611310),
        name: 'updatedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5832159942945371575),
        name: 'remoteUpdatedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5253294807579552108),
        name: 'syncState',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8922167803272805751),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 9107254583230726546),
    lastIndexId: const obx_int.IdUid(1, 3770003775933858745),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    OfflineSyncRecord: obx_int.EntityDefinition<OfflineSyncRecord>(
      model: _entities[0],
      toOneRelations: (OfflineSyncRecord object) => [],
      toManyRelations: (OfflineSyncRecord object) => {},
      getId: (OfflineSyncRecord object) => object.id,
      setId: (OfflineSyncRecord object, int id) {
        object.id = id;
      },
      objectToFB: (OfflineSyncRecord object, fb.Builder fbb) {
        final cacheKeyOffset = fbb.writeString(object.cacheKey);
        final modelTypeOffset = fbb.writeString(object.modelType);
        final recordUuidOffset = fbb.writeString(object.recordUuid);
        final payloadJsonOffset = fbb.writeString(object.payloadJson);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cacheKeyOffset);
        fbb.addOffset(2, modelTypeOffset);
        fbb.addOffset(3, recordUuidOffset);
        fbb.addOffset(4, payloadJsonOffset);
        fbb.addInt64(5, object.updatedAtMillis);
        fbb.addInt64(6, object.remoteUpdatedAtMillis);
        fbb.addInt64(7, object.syncState);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cacheKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final modelTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final recordUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final updatedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final remoteUpdatedAtMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final syncStateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = OfflineSyncRecord(
          id: idParam,
          cacheKey: cacheKeyParam,
          modelType: modelTypeParam,
          recordUuid: recordUuidParam,
          payloadJson: payloadJsonParam,
          updatedAtMillis: updatedAtMillisParam,
          remoteUpdatedAtMillis: remoteUpdatedAtMillisParam,
          syncState: syncStateParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OfflineSyncRecord] entity fields to define ObjectBox queries.
class OfflineSyncRecord_ {
  /// See [OfflineSyncRecord.id].
  static final id = obx.QueryIntegerProperty<OfflineSyncRecord>(
    _entities[0].properties[0],
  );

  /// See [OfflineSyncRecord.cacheKey].
  static final cacheKey = obx.QueryStringProperty<OfflineSyncRecord>(
    _entities[0].properties[1],
  );

  /// See [OfflineSyncRecord.modelType].
  static final modelType = obx.QueryStringProperty<OfflineSyncRecord>(
    _entities[0].properties[2],
  );

  /// See [OfflineSyncRecord.recordUuid].
  static final recordUuid = obx.QueryStringProperty<OfflineSyncRecord>(
    _entities[0].properties[3],
  );

  /// See [OfflineSyncRecord.payloadJson].
  static final payloadJson = obx.QueryStringProperty<OfflineSyncRecord>(
    _entities[0].properties[4],
  );

  /// See [OfflineSyncRecord.updatedAtMillis].
  static final updatedAtMillis = obx.QueryIntegerProperty<OfflineSyncRecord>(
    _entities[0].properties[5],
  );

  /// See [OfflineSyncRecord.remoteUpdatedAtMillis].
  static final remoteUpdatedAtMillis =
      obx.QueryIntegerProperty<OfflineSyncRecord>(_entities[0].properties[6]);

  /// See [OfflineSyncRecord.syncState].
  static final syncState = obx.QueryIntegerProperty<OfflineSyncRecord>(
    _entities[0].properties[7],
  );

  /// See [OfflineSyncRecord.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<OfflineSyncRecord>(
    _entities[0].properties[8],
  );
}
